import 'package:flutter/material.dart';import 'package:prototype_final/core/app_export.dart';import 'package:prototype_final/widgets/app_bar/appbar_leading_image.dart';import 'package:prototype_final/widgets/app_bar/appbar_title.dart';import 'package:prototype_final/widgets/app_bar/custom_app_bar.dart';class CommuteScreen extends StatelessWidget {const CommuteScreen({Key? key}) : super(key: key);

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(body: SizedBox(width: double.maxFinite, child: SizedBox(height: 797.v, width: double.maxFinite, child: Stack(alignment: Alignment.topCenter, children: [Align(alignment: Alignment.center, child: Container(padding: EdgeInsets.symmetric(horizontal: 8.h, vertical: 19.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 75.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("From the airport", style: CustomTextStyles.titleLargeBold)), SizedBox(height: 16.v), Align(alignment: Alignment.center, child: Container(width: 333.h, margin: EdgeInsets.only(left: 16.h, right: 24.h), child: Text("Transportation from the Airport: New Chitose Airport offers various transportation options to reach your desired destination in Hokkaido. These include airport limousine buses, train services such as the JR Hokkaido line, and taxis. Research and plan your preferred mode of transportation in advance based on your destination and budget.", maxLines: 8, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyLargeBlack9000116_1.copyWith(height: 1.50)))), SizedBox(height: 15.v), Padding(padding: EdgeInsets.only(left: 16.h), child: Text("By JR", style: CustomTextStyles.titleLargeBold)), SizedBox(height: 16.v), Align(alignment: Alignment.center, child: Container(width: 340.h, margin: EdgeInsets.only(left: 16.h, right: 17.h), child: Text("Hokkaido JR is the railway network that connects major cities and towns in Hokkaido, Japan's northernmost island. It offers convenient transportation for travelers, allowing them to explore the region's natural wonders, cultural attractions, and culinary delights with ease.", maxLines: 6, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyLargeBluegray9000316.copyWith(height: 1.50)))), SizedBox(height: 12.v), CustomImageView(imagePath: ImageConstant.imgScreenShot20230410, height: 238.v, width: 358.h, margin: EdgeInsets.only(left: 16.h))]))), _buildArrowLeft(context)]))))); } 
/// Section Widget
Widget _buildArrowLeft(BuildContext context) { return Align(alignment: Alignment.topCenter, child: Column(mainAxisSize: MainAxisSize.min, children: [Container(decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.customBorderTL20), child: CustomAppBar(height: 40.v, leadingWidth: 48.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftWhiteA70040x32, margin: EdgeInsets.only(left: 16.h), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarTitle(text: "Hokkaido: Info"))), Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 24.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 9.v), child: Text("General", style: CustomTextStyles.titleSmallBluegray400)), GestureDetector(onTap: () {onTapTxtInformation(context);}, child: Padding(padding: EdgeInsets.only(bottom: 9.v), child: Text("Info for Travellers", style: CustomTextStyles.titleSmallBluegray400))), Padding(padding: EdgeInsets.only(bottom: 9.v), child: Text("Commute", style: CustomTextStyles.titleSmallCyan700))]))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the infoForTravellerTabContainerScreen when the action is triggered.
onTapTxtInformation(BuildContext context) { Navigator.pushNamed(context, AppRoutes.infoForTravellerTabContainerScreen); } 
 }
