import 'package:flutter/material.dart';import 'package:prototype_final/core/app_export.dart';import 'package:prototype_final/widgets/app_bar/appbar_leading_image.dart';import 'package:prototype_final/widgets/app_bar/appbar_subtitle_four.dart';import 'package:prototype_final/widgets/app_bar/appbar_trailing_image.dart';import 'package:prototype_final/widgets/app_bar/custom_app_bar.dart';import 'package:prototype_final/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class AichatbotScreen extends StatelessWidget {AichatbotScreen({Key? key}) : super(key: key);

TextEditingController group265Controller = TextEditingController();

TextEditingController messageController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: SizedBox(width: double.maxFinite, child: Container(padding: EdgeInsets.symmetric(vertical: 12.v), decoration: AppDecoration.fillWhiteA.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildAppBar(context), SizedBox(height: 29.v), SizedBox(width: 196.h, child: Text("Hello, Ask Me \nAnything...", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.headlineLargeInterBlack90001)), SizedBox(height: 26.v), Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 111.h), child: Text("Last Update: 6.11 2023", style: CustomTextStyles.titleSmallInterBlack90001))), SizedBox(height: 32.v), Padding(padding: EdgeInsets.only(left: 29.h, right: 18.h), child: CustomTextFormField(controller: group265Controller, hintText: "can you plan a two-day trip to tokyo?", hintStyle: CustomTextStyles.titleMediumInterGray40002, contentPadding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 14.v), borderDecoration: TextFormFieldStyleHelper.outlineGrayTL25, fillColor: appTheme.gray100)), SizedBox(height: 34.v), _buildNinetyTwo(context), SizedBox(height: 34.v), _buildNinetyThree(context), SizedBox(height: 34.v), _buildNinetyFour(context), SizedBox(height: 34.v), _buildNinetyFive(context), SizedBox(height: 97.v), Padding(padding: EdgeInsets.only(left: 29.h, right: 17.h), child: CustomTextFormField(controller: messageController, hintText: "Message here...", textInputAction: TextInputAction.done, suffix: Container(padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 10.v), margin: EdgeInsets.fromLTRB(30.h, 8.v, 8.h, 8.v), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(17.h)), child: CustomImageView(imagePath: ImageConstant.imgArrowup, height: 14.v, width: 10.h)), suffixConstraints: BoxConstraints(maxHeight: 50.v), borderDecoration: TextFormFieldStyleHelper.outlineGrayTL25, fillColor: appTheme.gray100)), SizedBox(height: 26.v)]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(leadingWidth: 50.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleFour(text: "AI-CHATBOT"), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgMenu, margin: EdgeInsets.symmetric(horizontal: 14.h, vertical: 4.v))]); } 
/// Section Widget
Widget _buildNinetyTwo(BuildContext context) { return Container(margin: EdgeInsets.only(left: 29.h, right: 18.h), padding: EdgeInsets.symmetric(horizontal: 9.h, vertical: 3.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder25), child: SizedBox(width: 320.h, child: Text("Can you recommend a business-friendly \nrestaurant in France?", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleMediumInterGray40002))); } 
/// Section Widget
Widget _buildNinetyThree(BuildContext context) { return Container(width: 343.h, margin: EdgeInsets.only(left: 25.h, right: 22.h), padding: EdgeInsets.symmetric(horizontal: 15.h, vertical: 1.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder25), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 2.v), Container(width: 272.h, margin: EdgeInsets.only(right: 38.h), child: Text("Check for air tickets to the UK on  \nFebruary 10.", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleMediumInterGray40002))])); } 
/// Section Widget
Widget _buildNinetyFour(BuildContext context) { return Container(width: 343.h, margin: EdgeInsets.only(left: 25.h, right: 22.h), padding: EdgeInsets.symmetric(horizontal: 4.h, vertical: 10.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder25), child: Column(mainAxisSize: MainAxisSize.min, mainAxisAlignment: MainAxisAlignment.end, children: [SizedBox(height: 7.v), Text("What items cannot be brought on board ?", style: CustomTextStyles.titleMediumInterGray40002)])); } 
/// Section Widget
Widget _buildNinetyFive(BuildContext context) { return Container(margin: EdgeInsets.only(left: 20.h, right: 27.h), padding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 3.v), decoration: AppDecoration.outlineGray.copyWith(borderRadius: BorderRadiusStyle.circleBorder25), child: SizedBox(width: 303.h, child: Text("Are there any grand events in Thailand \nin November?", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.titleMediumInterGray40002))); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
