import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:prototype_final/core/app_export.dart';import 'package:prototype_final/widgets/app_bar/appbar_leading_image.dart';import 'package:prototype_final/widgets/app_bar/appbar_subtitle_four.dart';import 'package:prototype_final/widgets/app_bar/appbar_trailing_circleimage.dart';import 'package:prototype_final/widgets/app_bar/custom_app_bar.dart';import 'package:prototype_final/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class AichatbottwoScreen extends StatelessWidget {AichatbottwoScreen({Key? key}) : super(key: key);

TextEditingController messageController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: 414.h, padding: EdgeInsets.symmetric(horizontal: 25.h, vertical: 12.v), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildAichatbot2(context), SizedBox(height: 279.v, width: 361.h), Spacer()])), bottomNavigationBar: _buildMessage(context))); } 
/// Section Widget
Widget _buildAichatbot2(BuildContext context) { return SizedBox(height: 279.v, width: 361.h, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topCenter, child: Container(margin: EdgeInsets.only(left: 63.h, top: 84.v, right: 63.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 11.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup6929), fit: BoxFit.cover)), child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 8.v), Container(width: 187.h, margin: EdgeInsets.only(right: 15.h), child: Text("Can You Plan A Two-Day Trip To Tokyo?", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyLargeInter))]))), Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomAppBar(leadingWidth: 60.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 28.h), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleFour(text: "AI-CHATBOT"), actions: [AppbarTrailingCircleimage(imagePath: ImageConstant.imgMenu, margin: EdgeInsets.symmetric(horizontal: 28.h, vertical: 4.v))]), SizedBox(height: 110.v), CustomImageView(imagePath: ImageConstant.imgRectangle37, height: 47.adaptSize, width: 47.adaptSize, radius: BorderRadius.circular(15.h), alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 5.h)), SizedBox(height: 89.v), SizedBox(width: 51.h, child: Divider(color: appTheme.blueGray100))]))])); } 
/// Section Widget
Widget _buildMessage(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 15.h, right: 6.h, bottom: 38.v), child: CustomTextFormField(controller: messageController, hintText: "Message here...", textInputAction: TextInputAction.done, suffix: Container(padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 10.v), margin: EdgeInsets.fromLTRB(30.h, 8.v, 8.h, 8.v), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(17.h)), child: CustomImageView(imagePath: ImageConstant.imgArrowup, height: 14.v, width: 10.h)), suffixConstraints: BoxConstraints(maxHeight: 50.v))); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
