import 'package:flutter/material.dart';import 'package:flutter_svg_provider/flutter_svg_provider.dart' as fs;import 'package:prototype_final/core/app_export.dart';import 'package:prototype_final/widgets/app_bar/appbar_leading_image.dart';import 'package:prototype_final/widgets/app_bar/appbar_subtitle_four.dart';import 'package:prototype_final/widgets/app_bar/appbar_trailing_circleimage.dart';import 'package:prototype_final/widgets/app_bar/custom_app_bar.dart';import 'package:prototype_final/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class AichatbottwoTwoScreen extends StatelessWidget {AichatbottwoTwoScreen({Key? key}) : super(key: key);

TextEditingController messageController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, body: Container(width: 414.h, padding: EdgeInsets.symmetric(vertical: 12.v), child: Column(mainAxisSize: MainAxisSize.min, children: [_buildArrowLeft(context), Container(padding: EdgeInsets.symmetric(horizontal: 31.h), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Align(alignment: Alignment.center, child: Container(width: 235.h, margin: EdgeInsets.symmetric(horizontal: 58.h), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 11.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup6929), fit: BoxFit.cover)), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [SizedBox(height: 8.v), Container(width: 187.h, margin: EdgeInsets.only(right: 15.h), child: Text("Can You Plan A Two-Day Trip To Tokyo?", maxLines: 2, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyLargeInter))]))), SizedBox(height: 33.v), Padding(padding: EdgeInsets.only(right: 59.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(height: 40.adaptSize, width: 40.adaptSize, margin: EdgeInsets.only(top: 456.v), child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.imgGroup6969, height: 40.adaptSize, width: 40.adaptSize, alignment: Alignment.center), CustomImageView(imagePath: ImageConstant.imgAiEssentialsIcon, height: 40.adaptSize, width: 40.adaptSize, radius: BorderRadius.circular(20.h), alignment: Alignment.center)])), Expanded(child: Container(margin: EdgeInsets.only(left: 18.h, bottom: 20.v), padding: EdgeInsets.symmetric(horizontal: 16.h, vertical: 8.v), decoration: BoxDecoration(image: DecorationImage(image: fs.Svg(ImageConstant.imgGroup98), fit: BoxFit.cover)), child: Column(children: [SizedBox(height: 53.v), Container(width: 198.h, margin: EdgeInsets.only(right: 4.h), child: Text("Certainly! Here's a two-day itinerary for your trip to Tokyo:\nDay 1:\nMorning:\nStart by visiting the iconic Shibuya Crossing, one of the busiest intersections in the world.\nExplore the Shibuya neighborhood, known for its trendy shops and vibrant atmosphere.\nAfternoon:\nVisit Yoyogi Park, a spacious green area adjacent to Harajuku.\n\n      ......", maxLines: 21, overflow: TextOverflow.ellipsis, style: CustomTextStyles.bodyLargeInterOnErrorContainer))])))])), SizedBox(height: 5.v)]))])), bottomNavigationBar: _buildMessage(context))); } 
/// Section Widget
Widget _buildArrowLeft(BuildContext context) { return Column(children: [CustomAppBar(leadingWidth: 60.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 28.h), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarSubtitleFour(text: "AI-CHATBOT"), actions: [AppbarTrailingCircleimage(imagePath: ImageConstant.imgMenu, margin: EdgeInsets.symmetric(horizontal: 28.h, vertical: 4.v))]), SizedBox(height: 110.v), CustomImageView(imagePath: ImageConstant.imgRectangle37, height: 47.adaptSize, width: 47.adaptSize, radius: BorderRadius.circular(15.h), alignment: Alignment.centerRight, margin: EdgeInsets.only(right: 33.h))]); } 
/// Section Widget
Widget _buildMessage(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 40.h, right: 31.h, bottom: 38.v), child: CustomTextFormField(controller: messageController, hintText: "Message here...", textInputAction: TextInputAction.done, suffix: Container(padding: EdgeInsets.symmetric(horizontal: 12.h, vertical: 10.v), margin: EdgeInsets.fromLTRB(30.h, 8.v, 8.h, 8.v), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(17.h)), child: CustomImageView(imagePath: ImageConstant.imgArrowup, height: 14.v, width: 10.h)), suffixConstraints: BoxConstraints(maxHeight: 50.v))); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
