import 'package:flutter/material.dart';import 'package:prototype_final/core/app_export.dart';import 'package:prototype_final/widgets/app_bar/appbar_leading_image.dart';import 'package:prototype_final/widgets/app_bar/appbar_title_image.dart';import 'package:prototype_final/widgets/app_bar/custom_app_bar.dart';import 'package:prototype_final/widgets/custom_elevated_button.dart';import 'package:prototype_final/widgets/custom_outlined_button.dart';import 'package:prototype_final/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class LoginScreen extends StatelessWidget {LoginScreen({Key? key}) : super(key: key);

TextEditingController loginEmailController = TextEditingController();

TextEditingController loginPasswordController = TextEditingController();

GlobalKey<FormState> _formKey = GlobalKey<FormState>();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: Form(key: _formKey, child: SingleChildScrollView(padding: EdgeInsets.only(top: 20.v), child: Padding(padding: EdgeInsets.only(left: 20.h), child: Column(children: [Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisAlignment: MainAxisAlignment.center, children: [SizedBox(height: 3.v), Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.only(bottom: 7.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [Container(width: 98.h, margin: EdgeInsets.only(right: 10.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, children: [Text("Mobile", style: CustomTextStyles.titleSmallOpenSansGray60001), Text("Email", style: CustomTextStyles.titleSmallOpenSansGray90001)])), SizedBox(height: 4.v), Align(alignment: Alignment.centerRight, child: SizedBox(width: 47.h, child: Divider(color: appTheme.gray90001)))])), Container(width: 85.h, margin: EdgeInsets.only(left: 20.h), child: Text("Membership\nnumber ", maxLines: 2, overflow: TextOverflow.ellipsis, textAlign: TextAlign.center, style: CustomTextStyles.titleSmallOpenSansGray60001))]), SizedBox(height: 21.v), _buildLoginEmail(context), SizedBox(height: 10.v), _buildLoginPassword(context), SizedBox(height: 12.v), Text("Forgot password  ?", style: CustomTextStyles.titleSmallPlusJakartaSansGray90001.copyWith(decoration: TextDecoration.underline)), SizedBox(height: 18.v), _buildLoginButton(context), SizedBox(height: 9.v), Padding(padding: EdgeInsets.only(right: 104.h), child: Row(children: [Padding(padding: EdgeInsets.only(bottom: 1.v), child: Text("Don’t have an account ? ", style: CustomTextStyles.bodyMediumPlusJakartaSansGray500)), Padding(padding: EdgeInsets.only(left: 3.h), child: Text("Create account", style: CustomTextStyles.titleSmallPlusJakartaSansGray90001.copyWith(decoration: TextDecoration.underline)))])), SizedBox(height: 22.v), _buildLoginFrame(context), SizedBox(height: 19.v), _buildLoginGoogleButton(context), SizedBox(height: 12.v), _buildLoginFacebookButton(context), SizedBox(height: 27.v), Container(width: 340.h, margin: EdgeInsets.only(right: 29.h), child: RichText(text: TextSpan(children: [TextSpan(text: " By sign in , you agree to our ", style: CustomTextStyles.titleSmallPlusJakartaSansBlack90001), TextSpan(text: "Terms & Conditions", style: CustomTextStyles.titleSmallPlusJakartaSansRed500.copyWith(decoration: TextDecoration.underline)), TextSpan(text: " and that you have read our Privacy Policy.", style: CustomTextStyles.titleSmallPlusJakartaSansRed500)]), textAlign: TextAlign.left))]), SizedBox(height: 118.v), Align(alignment: Alignment.centerRight, child: SizedBox(width: 245.h, child: Divider(color: appTheme.black90001, endIndent: 105.h)))])))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 144.v, leadingWidth: 54.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftGray90001, margin: EdgeInsets.only(left: 30.h, top: 19.v, bottom: 83.v), onTap: () {onTapArrowLeft(context);}), centerTitle: true, title: AppbarTitleImage(imagePath: ImageConstant.imgCathay11126x184)); } 
/// Section Widget
Widget _buildLoginEmail(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 22.h), child: CustomTextFormField(controller: loginEmailController, hintText: "Enter your email", hintStyle: CustomTextStyles.titleSmallPlusJakartaSansGray500, textInputType: TextInputType.emailAddress, contentPadding: EdgeInsets.symmetric(horizontal: 17.h, vertical: 19.v))); } 
/// Section Widget
Widget _buildLoginPassword(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 22.h), child: CustomTextFormField(controller: loginPasswordController, hintText: "Password", hintStyle: CustomTextStyles.titleSmallPlusJakartaSansGray500, textInputAction: TextInputAction.done, textInputType: TextInputType.visiblePassword, suffix: Container(margin: EdgeInsets.fromLTRB(30.h, 14.v, 17.h, 16.v), child: CustomImageView(imagePath: ImageConstant.imgCloseBlueGray900, height: 24.adaptSize, width: 24.adaptSize)), suffixConstraints: BoxConstraints(maxHeight: 54.v), obscureText: true, contentPadding: EdgeInsets.only(left: 15.h, top: 18.v, bottom: 18.v))); } 
/// Section Widget
Widget _buildLoginButton(BuildContext context) { return CustomElevatedButton(height: 58.v, text: "Login", margin: EdgeInsets.only(right: 22.h), buttonTextStyle: CustomTextStyles.titleSmallPlusJakartaSansWhiteA700, onPressed: () {onTapLoginButton(context);}); } 
/// Section Widget
Widget _buildLoginFrame(BuildContext context) { return Padding(padding: EdgeInsets.only(right: 22.h), child: Row(crossAxisAlignment: CrossAxisAlignment.start, children: [Padding(padding: EdgeInsets.symmetric(vertical: 8.v), child: SizedBox(width: 155.h, child: Divider(color: appTheme.gray500))), Padding(padding: EdgeInsets.only(left: 8.h), child: Text("OR", style: CustomTextStyles.titleSmallPlusJakartaSansGray500)), Padding(padding: EdgeInsets.symmetric(vertical: 8.v), child: SizedBox(width: 163.h, child: Divider(color: appTheme.gray500, indent: 8.h)))])); } 
/// Section Widget
Widget _buildLoginGoogleButton(BuildContext context) { return CustomOutlinedButton(height: 56.v, text: "Continue with Google ", margin: EdgeInsets.only(right: 21.h), leftIcon: Container(margin: EdgeInsets.only(right: 25.h), child: CustomImageView(imagePath: ImageConstant.imgGoogle, height: 24.adaptSize, width: 24.adaptSize)), buttonStyle: CustomButtonStyles.outlineGray); } 
/// Section Widget
Widget _buildLoginFacebookButton(BuildContext context) { return CustomOutlinedButton(height: 56.v, text: "Continue with Facebook", margin: EdgeInsets.only(right: 22.h), leftIcon: Container(margin: EdgeInsets.only(right: 25.h), child: CustomImageView(imagePath: ImageConstant.imgFacebook, height: 24.adaptSize, width: 24.adaptSize)), buttonStyle: CustomButtonStyles.outlineGrayTL8); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the homePageContainerScreen when the action is triggered.
onTapLoginButton(BuildContext context) { Navigator.pushNamed(context, AppRoutes.homePageContainerScreen); } 
 }
