import '../home1_page/widgets/homepage_item_widget.dart';import 'package:flutter/material.dart';import 'package:prototype_final/core/app_export.dart';import 'package:prototype_final/widgets/app_bar/appbar_subtitle_six.dart';import 'package:prototype_final/widgets/app_bar/appbar_title_image.dart';import 'package:prototype_final/widgets/app_bar/appbar_trailing_image.dart';import 'package:prototype_final/widgets/app_bar/custom_app_bar.dart';import 'package:prototype_final/widgets/custom_outlined_button.dart';import 'package:prototype_final/widgets/custom_search_view.dart';import 'package:prototype_final/widgets/custom_text_form_field.dart';
// ignore_for_file: must_be_immutable
class Home1Page extends StatelessWidget {Home1Page({Key? key}) : super(key: key);

TextEditingController searchController = TextEditingController();

TextEditingController homePageWeatherController = TextEditingController();

@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.gray100, resizeToAvoidBottomInset: false, appBar: _buildAppBar(context), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 11.v), child: Column(crossAxisAlignment: CrossAxisAlignment.start, children: [_buildHomePageSearch(context), SizedBox(height: 8.v), _buildExploreSection(context), SizedBox(height: 14.v), CustomImageView(imagePath: ImageConstant.imgRectangle122, height: 195.v, width: 343.h, radius: BorderRadius.circular(20.h), alignment: Alignment.center), SizedBox(height: 7.v), Padding(padding: EdgeInsets.only(left: 31.h), child: Text("Winter Trip 2023", style: CustomTextStyles.titleLargePrimary)), Padding(padding: EdgeInsets.only(left: 31.h), child: Text("16 Jan - 26 Jan", style: CustomTextStyles.bodyMediumPrimary_1)), Padding(padding: EdgeInsets.only(left: 31.h), child: Text("Hokkaido", style: CustomTextStyles.bodyMediumPrimary_1)), SizedBox(height: 6.v), _buildPopularDestinationsSection(context), SizedBox(height: 10.v), _buildLatestNewsSection(context), SizedBox(height: 37.v), Container(height: 8.adaptSize, width: 8.adaptSize, margin: EdgeInsets.only(left: 31.h), decoration: BoxDecoration(color: theme.colorScheme.primary, borderRadius: BorderRadius.circular(4.h)))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 71.v, title: Padding(padding: EdgeInsets.only(left: 22.h), child: Column(children: [Align(alignment: Alignment.centerLeft, child: Padding(padding: EdgeInsets.only(left: 1.h, right: 29.h), child: RichText(text: TextSpan(children: [TextSpan(text: "Hi, ", style: CustomTextStyles.titleLargeInterGray70002SemiBold), TextSpan(text: "Username", style: CustomTextStyles.titleLargeInterGray70002SemiBold.copyWith(decoration: TextDecoration.underline))]), textAlign: TextAlign.left))), SizedBox(height: 6.v), Row(children: [AppbarTitleImage(imagePath: ImageConstant.imgLocationGray80003, margin: EdgeInsets.only(bottom: 6.v)), AppbarSubtitleSix(text: "Hokkaido, Japan", margin: EdgeInsets.only(left: 5.h)), AppbarTitleImage(imagePath: ImageConstant.imgLocationPrimary7x10, margin: EdgeInsets.only(left: 4.h, top: 8.v, bottom: 5.v))])])), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgIcon, margin: EdgeInsets.only(left: 28.h, top: 12.v, right: 19.h), onTap: () {onTapIcon(context);}), AppbarTrailingImage(imagePath: ImageConstant.imgHomePageNotification, margin: EdgeInsets.only(left: 14.h, top: 13.v, right: 47.h))]); } 
/// Section Widget
Widget _buildHomePageSearch(BuildContext context) { return Align(alignment: Alignment.center, child: Padding(padding: EdgeInsets.symmetric(horizontal: 22.h), child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Expanded(child: CustomSearchView(controller: searchController, hintText: "Search", hintStyle: CustomTextStyles.bodyLargeInterGray40001, contentPadding: EdgeInsets.only(left: 30.h, top: 12.v, bottom: 12.v), borderDecoration: SearchViewStyleHelper.custom, filled: false)), Container(height: 46.v, width: 43.h, margin: EdgeInsets.only(left: 5.h), padding: EdgeInsets.symmetric(horizontal: 10.h, vertical: 12.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.roundedBorder8), child: CustomImageView(imagePath: ImageConstant.imgImage4, height: 21.adaptSize, width: 21.adaptSize, alignment: Alignment.center))]))); } 
/// Section Widget
Widget _buildExploreButton(BuildContext context) { return CustomOutlinedButton(width: 97.h, text: "Explore", margin: EdgeInsets.only(left: 9.h), leftIcon: Container(margin: EdgeInsets.only(right: 7.h), child: CustomImageView(imagePath: ImageConstant.imgDesignToolsEye, height: 24.adaptSize, width: 24.adaptSize)), buttonTextStyle: CustomTextStyles.bodySmallGray900, onPressed: () {onTapExploreButton(context);}); } 
/// Section Widget
Widget _buildHomePageWeather(BuildContext context) { return Padding(padding: EdgeInsets.only(left: 5.h), child: CustomTextFormField(width: 103.h, controller: homePageWeatherController, hintText: "Weather", hintStyle: CustomTextStyles.bodySmallGray900, textInputAction: TextInputAction.done, prefix: Container(margin: EdgeInsets.fromLTRB(4.h, 5.v, 3.h, 5.v), child: CustomImageView(imagePath: ImageConstant.imgSnowy, height: 30.adaptSize, width: 30.adaptSize)), prefixConstraints: BoxConstraints(maxHeight: 40.v), contentPadding: EdgeInsets.only(top: 12.v, right: 17.h, bottom: 12.v), borderDecoration: TextFormFieldStyleHelper.outlineGrayTL20, fillColor: appTheme.whiteA700)); } 
/// Section Widget
Widget _buildExchangeButton(BuildContext context) { return CustomOutlinedButton(width: 103.h, text: "Exchange", margin: EdgeInsets.only(left: 7.h), leftIcon: Container(margin: EdgeInsets.only(right: 3.h), child: CustomImageView(imagePath: ImageConstant.imgUserInterfaceDonate, height: 24.adaptSize, width: 24.adaptSize)), buttonTextStyle: CustomTextStyles.bodySmallGray900, onPressed: () {onTapExchangeButton(context);}); } 
/// Section Widget
Widget _buildExploreSection(BuildContext context) { return SingleChildScrollView(scrollDirection: Axis.horizontal, padding: EdgeInsets.only(left: 11.h), child: IntrinsicWidth(child: Row(mainAxisAlignment: MainAxisAlignment.center, children: [Container(width: 97.h, decoration: AppDecoration.outlinePrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: Row(children: [Container(height: 40.v, width: 38.h, padding: EdgeInsets.symmetric(horizontal: 3.h, vertical: 4.v), decoration: AppDecoration.fillPrimary.copyWith(borderRadius: BorderRadiusStyle.circleBorder20), child: CustomImageView(imagePath: ImageConstant.imgImage5, height: 31.adaptSize, width: 31.adaptSize, alignment: Alignment.center)), Padding(padding: EdgeInsets.only(left: 6.h, top: 14.v, bottom: 11.v), child: Text("My trip", style: CustomTextStyles.bodySmallGray900))])), _buildExploreButton(context), _buildHomePageWeather(context), _buildExchangeButton(context)]))); } 
/// Section Widget
Widget _buildPopularDestinationsSection(BuildContext context) { return Align(alignment: Alignment.centerRight, child: Container(height: 123.v, width: 355.h, margin: EdgeInsets.only(right: 7.h), child: Stack(alignment: Alignment.bottomCenter, children: [Align(alignment: Alignment.topLeft, child: Text("Popular Destinations", style: CustomTextStyles.titleLargePrimary)), Align(alignment: Alignment.bottomCenter, child: SizedBox(height: 123.v, child: ListView.separated(padding: EdgeInsets.only(left: 2.h, top: 23.v), scrollDirection: Axis.horizontal, separatorBuilder: (context, index) {return SizedBox(width: 16.h);}, itemCount: 2, itemBuilder: (context, index) {return HomepageItemWidget();})))]))); } 
/// Section Widget
Widget _buildLatestNewsSection(BuildContext context) { return Container(height: 233.v, width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 28.h), child: Stack(alignment: Alignment.topLeft, children: [CustomImageView(imagePath: ImageConstant.imgFrame15, height: 113.v, width: 188.h, alignment: Alignment.topLeft, margin: EdgeInsets.only(top: 14.v)), Align(alignment: Alignment.topLeft, child: Text("Latest News", style: CustomTextStyles.titleLargePrimary))])); } 
/// Navigates to the aichatbotScreen when the action is triggered.
onTapIcon(BuildContext context) { Navigator.pushNamed(context, AppRoutes.aichatbotScreen); } 
/// Navigates to the exploreTabContainerScreen when the action is triggered.
onTapExploreButton(BuildContext context) { Navigator.pushNamed(context, AppRoutes.exploreTabContainerScreen); } 
/// Navigates to the currencyConverterScreen when the action is triggered.
onTapExchangeButton(BuildContext context) { Navigator.pushNamed(context, AppRoutes.currencyConverterScreen); } 
 }
