import 'package:flutter/material.dart';import 'package:prototype_final/core/app_export.dart';import 'package:prototype_final/presentation/airport_map_page/airport_map_page.dart';import 'package:prototype_final/widgets/app_bar/appbar_leading_image.dart';import 'package:prototype_final/widgets/app_bar/appbar_trailing_image.dart';import 'package:prototype_final/widgets/app_bar/custom_app_bar.dart';class AirportMapTabContainerScreen extends StatefulWidget {const AirportMapTabContainerScreen({Key? key}) : super(key: key);

@override AirportMapTabContainerScreenState createState() =>  AirportMapTabContainerScreenState();

 }

// ignore_for_file: must_be_immutable
class AirportMapTabContainerScreenState extends State<AirportMapTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 3, vsync: this); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.indigo50.withOpacity(0.5), body: SizedBox(height: 791.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [_buildTrackingSection(context), Align(alignment: Alignment.center, child: SizedBox(height: 791.v, width: double.maxFinite, child: Stack(alignment: Alignment.center, children: [CustomImageView(imagePath: ImageConstant.img02CathayPacif, height: 791.v, width: 390.h, alignment: Alignment.center), SizedBox(width: double.maxFinite, child: Align(alignment: Alignment.center, child: Column(mainAxisSize: MainAxisSize.min, crossAxisAlignment: CrossAxisAlignment.start, children: [_buildTabview(context), Expanded(child: SizedBox(height: 730.v, child: TabBarView(controller: tabviewController, children: [AirportMapPage(), AirportMapPage(), AirportMapPage()])))]))), _buildAppBarSection(context), _buildTopBarSection(context)])))])))); } 
/// Section Widget
Widget _buildTrackingSection(BuildContext context) { return Align(alignment: Alignment.topCenter, child: Padding(padding: EdgeInsets.fromLTRB(26.h, 308.v, 26.h, 459.v), child: Row(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [Padding(padding: EdgeInsets.only(top: 2.v), child: Text("Tracking", style: CustomTextStyles.titleSmallPoppinsBlack90001SemiBold)), Spacer(), Padding(padding: EdgeInsets.only(top: 2.v, bottom: 3.v), child: Text("Details", style: CustomTextStyles.labelLargePoppinsPrimary)), CustomImageView(imagePath: ImageConstant.imgInfo, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(left: 9.h))]))); } 
/// Section Widget
Widget _buildTabview(BuildContext context) { return Container(height: 32.v, width: 343.h, margin: EdgeInsets.only(left: 16.h), decoration: BoxDecoration(color: appTheme.indigo50, borderRadius: BorderRadius.circular(8.h)), child: TabBar(controller: tabviewController, labelPadding: EdgeInsets.zero, labelColor: appTheme.black90001, labelStyle: TextStyle(fontSize: 13.fSize, fontFamily: 'Lato', fontWeight: FontWeight.w900), unselectedLabelColor: appTheme.black90001, unselectedLabelStyle: TextStyle(fontSize: 13.fSize, fontFamily: 'Lato', fontWeight: FontWeight.w500), indicatorPadding: EdgeInsets.all(2.0.h), indicator: BoxDecoration(color: appTheme.whiteA700, borderRadius: BorderRadius.circular(6.h), border: Border.all(color: appTheme.black90001.withOpacity(0.04), width: 1.h, strokeAlign: strokeAlignOutside), boxShadow: [BoxShadow(color: appTheme.black90001.withOpacity(0.04), spreadRadius: 2.h, blurRadius: 2.h, offset: Offset(0, 3))]), tabs: [Tab(child: Text("􀙊 Itinerary")), Tab(child: Text("Baggage")), Tab(child: Text("Map"))])); } 
/// Section Widget
PreferredSizeWidget _buildAppBarSection(BuildContext context) { return CustomAppBar(height: 20.v, leadingWidth: 50.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeft, margin: EdgeInsets.only(left: 18.h), onTap: () {onTapArrowLeft(context);}), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgMenu, margin: EdgeInsets.fromLTRB(28.h, 1.v, 28.h, 8.v))]); } 
/// Section Widget
Widget _buildTopBarSection(BuildContext context) { return Align(alignment: Alignment.topCenter, child: Container(height: 27.v, width: double.maxFinite, decoration: AppDecoration.fillWhiteA, child: Stack(alignment: Alignment.center, children: [Align(alignment: Alignment.topCenter, child: Text("Airport Map", style: theme.textTheme.titleLarge)), Align(alignment: Alignment.center, child: Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 18.h), child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgArrowLeft, height: 20.v, width: 32.h, margin: EdgeInsets.only(bottom: 7.v)), GestureDetector(onTap: () {onTapTxtDone(context);}, child: Padding(padding: EdgeInsets.only(right: 18.h, bottom: 13.v), child: Text("Done", style: CustomTextStyles.bodyLargePrimary)))])))]))); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
/// Navigates to the flightDetailScreen when the action is triggered.
onTapTxtDone(BuildContext context) { Navigator.pushNamed(context, AppRoutes.flightDetailScreen); } 
 }
