import 'package:flutter/material.dart';import 'package:prototype_final/core/app_export.dart';import 'package:prototype_final/presentation/flight_listing_departure_page/flight_listing_departure_page.dart';import 'package:prototype_final/widgets/app_bar/appbar_leading_image.dart';import 'package:prototype_final/widgets/app_bar/appbar_trailing_image.dart';import 'package:prototype_final/widgets/app_bar/custom_app_bar.dart';class FlightListingDepartureTabContainerScreen extends StatefulWidget {const FlightListingDepartureTabContainerScreen({Key? key}) : super(key: key);

@override FlightListingDepartureTabContainerScreenState createState() =>  FlightListingDepartureTabContainerScreenState();

 }

// ignore_for_file: must_be_immutable
class FlightListingDepartureTabContainerScreenState extends State<FlightListingDepartureTabContainerScreen> with  TickerProviderStateMixin {late TabController tabviewController;

@override void initState() { super.initState(); tabviewController = TabController(length: 8, vsync: this); } 
@override Widget build(BuildContext context) { mediaQueryData = MediaQuery.of(context); return SafeArea(child: Scaffold(backgroundColor: appTheme.gray10002, appBar: _buildAppBar(context), body: SizedBox(width: mediaQueryData.size.width, child: SingleChildScrollView(padding: EdgeInsets.only(top: 8.v), child: Column(children: [_buildListItem(context), _buildTabview(context), SizedBox(height: 641.v, child: TabBarView(controller: tabviewController, children: [FlightListingDeparturePage(), FlightListingDeparturePage(), FlightListingDeparturePage(), FlightListingDeparturePage(), FlightListingDeparturePage(), FlightListingDeparturePage(), FlightListingDeparturePage(), FlightListingDeparturePage()]))]))))); } 
/// Section Widget
PreferredSizeWidget _buildAppBar(BuildContext context) { return CustomAppBar(height: 48.v, leadingWidth: 43.h, leading: AppbarLeadingImage(imagePath: ImageConstant.imgArrowLeftWhiteA700, margin: EdgeInsets.only(left: 10.h, bottom: 25.v), onTap: () {onTapArrowLeft(context);}), title: Padding(padding: EdgeInsets.only(left: 1.h), child: RichText(text: TextSpan(children: [TextSpan(text: "       Sapporo", style: CustomTextStyles.bodyLargeFiraSans), TextSpan(text: " (", style: CustomTextStyles.titleLargeFiraSansWhiteA700Regular), TextSpan(text: "CTS", style: CustomTextStyles.titleLargeFiraSansWhiteA700Regular), TextSpan(text: ")", style: CustomTextStyles.titleLargeFiraSansWhiteA700Regular)]), textAlign: TextAlign.left)), actions: [AppbarTrailingImage(imagePath: ImageConstant.imgMenuWhiteA70023x24, margin: EdgeInsets.only(left: 13.h, right: 13.h, bottom: 25.v))], styleType: Style.bgOutline_1); } 
/// Section Widget
Widget _buildListItem(BuildContext context) { return Container(width: double.maxFinite, padding: EdgeInsets.symmetric(horizontal: 97.h, vertical: 4.v), decoration: AppDecoration.gradientPrimaryToPrimary1, child: Row(mainAxisAlignment: MainAxisAlignment.spaceBetween, crossAxisAlignment: CrossAxisAlignment.start, children: [CustomImageView(imagePath: ImageConstant.imgIconWrapperWhiteA700, height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 8.v)), Padding(padding: EdgeInsets.only(top: 5.v, bottom: 8.v), child: Text("2 Adults - Economy", style: CustomTextStyles.titleSmallInterWhiteA700Medium)), Container(height: 24.adaptSize, width: 24.adaptSize, margin: EdgeInsets.only(bottom: 8.v), padding: EdgeInsets.all(3.h), decoration: AppDecoration.outlineWhiteA.copyWith(borderRadius: BorderRadiusStyle.circleBorder12), child: CustomImageView(imagePath: ImageConstant.imgIconWrapperWhiteA70016x16, height: 16.adaptSize, width: 16.adaptSize, alignment: Alignment.center))])); } 
/// Section Widget
Widget _buildTabview(BuildContext context) { return Container(height: 63.v, width: double.maxFinite, decoration: BoxDecoration(color: appTheme.whiteA700), child: TabBar(controller: tabviewController, isScrollable: true, labelColor: appTheme.whiteA700, unselectedLabelColor: theme.colorScheme.secondaryContainer, tabs: [Tab(child: Text("19/11/2023")), Tab(child: Text("Sun")), Tab(child: Text("20/11/2023")), Tab(child: Text("Mon")), Tab(child: Text("21/11/2023")), Tab(child: Text("Thus")), Tab(child: Text("22/11/2023")), Tab(child: Text("Wed"))])); } 

/// Navigates back to the previous screen.
onTapArrowLeft(BuildContext context) { Navigator.pop(context); } 
 }
